import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import { Home } from "@/components/views/Home";
import { Header } from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Pin Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
};

export default HomePage;
